# Generated by Django 4.1.5 on 2023-01-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websait', '0002_webhi_alter_webdev_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhI',
        ),
    ]
